### ISSUE TITLE
Does library handle the deletion of the expired key in param store?

### ISSUE THREAD

**Issue by mzbac** [aws/aws-ssm-data-protection-provider-for-aspnet#12]
Wondering how the expired key being handled. couldn't find any documentation about how to clean up the expired DataProtection key.. Is it something the end user have to handle it themselves. or it already handled somewhere in the library?

**Comment by klaytaybai** [comment]
Hi @mzbac, what are you hoping to do?  If you are only trying to ensure that the key is deleted, I think this is done automatically when it expires. It looks like we would need to add support for adding expiration notification policies.

**Comment by mzbac** [comment]
Hi @klaytaybai,
Thanks for your prompt reply. I just try to verify all those expired key will be deleted by the sdk. To me aws parameters store doesn't have mechanism to delete the keys itself. Wondering if that bit is handled in the sdk.

**Comment by klaytaybai** [comment]
As noted in the [SSM documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-policies.html), the SSM parameter store service deletes the expired ones automatically without need for user action.  However, this library currently doesn't set an expiration policy within the SSM service.  After reading https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-2.2, I'm thinking we should add more support for making the setting of expiration policies easier. Do you think this is necessary?

**Comment by mzbac** [comment]
Currently we using it for one of our key service on prod..we may have to clean up the expired the keys every three month.. If the library can support the expiration policy that will be great.

**Comment by LeeWortley** [comment]
I am looking at using this in a new project, are there any plans to implement this feature in the near future?

**Comment by ganeshnj** [comment]
Expired keys are still being used to unprotect data previously protected by that key. Also, we have no way of knowing how customers use the key, therefore, deleting a key will make all protected data by that key permanently undecipherable.

Technically you can create [parameters with expiration](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-policies.html) but not recommended for this use case.

You can check [Microsoft's recommendation](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-3.1) on deletion of the keys that weighs same.

**Comment by mzbac** [comment]
@ganeshnj thanks for the details explanation. Make a lot sense.
