### ISSUE TITLE
Feature request: Allow custom IAmazonSimpleSystemsManagement client usage

### ISSUE THREAD

**Issue by clearwaterstream** [aws/aws-ssm-data-protection-provider-for-aspnet#13]
I use a specialized AmazonSimpleSystemsManagementClient instance and I would like to re-use it for this purpose as well.

If I simply follow the doc and do

```csharp
services.AddDataProtection()
	.PersistKeysToAWSSystemsManager("/MyApplication/DataProtection");
```

then a default singleton instance of AmazonSimpleSystemsManagementClient would be used. All good (in most cases) except in my case I need to use my own version.

I was thinking something like:

```csharp
services.AddDataProtection()
	.PersistKeysToAWSSystemsManager($"/MyApplication/DataProtection", setupAction =>
	{
		setupAction.SsmClientResolver = () => { return my_ssm_client  };
	});
```

Change would be in `PersistKeysToAWSSystemsManager` method in https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/src/Amazon.AspNetCore.DataProtection.SSM/ExtensionMethods.cs

If `SsmClientResolver` func is null, then call `services.GetService<IAmazonSimpleSystemsManagement>();` as you to today.

I have a way around this, but this would make it very simple. Thanks!!

**Comment by clearwaterstream** [comment]
P.S. the code I'm currently using to achieve this:

```csharp
services.AddDataProtection()
	.PersistKeysToAWSSystemsManager("/MyApplication/DataProtection");

var ssmClientDesc = new ServiceDescriptor(typeof(IAmazonSimpleSystemsManagement), (svcProvider) => { return my_ssm_client; }, ServiceLifetime.Singleton);

services.Replace(ssmClientDesc);
```

**Comment by klaytaybai** [comment]
Thanks for the feedback.  It seems like something we may consider.

**Comment by maulik-modi** [comment]
@ashovlin , I think this is a reasonable request with more flexible option, code changes are also mentioned by @clearwaterstream

**Comment by maulik-modi** [comment]
@YuxuanLin , Is it possible to consider this?

**Comment by csantos** [comment]
Since the PersistKeystoAWSSystemsManager method [makes a call](https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/fe22951eedb48be7fb4c0a89ce71e7a86c3ff690/src/Amazon.AspNetCore.DataProtection.SSM/ExtensionMethods.cs#L65) to TryAddAWSService<IAmazonSimpleSystemsManagement>(), why not just call services.AddSingleton prior to the call to PersistKeystoAWSSystemsManager. Something like:

```csharp
services.AddSingleton<IAmazonSimpleSystemsManagement>(my_ssm_client)
        .AddDataProtection()
	.PersistKeysToAWSSystemsManager("/MyApplication/DataProtection");

```

That will make your instance have priority over what the SDK would register.

**Comment by normj** [comment]
I agree with @csantos. If you want a custom implementation just add your implementation into the service collection before calling `PersistKeysToAWSSystemsManager`. I don't want to create a second way to do the same thing the build in DI is handling for you.
