### ISSUE TITLE
How to handle failed fetch?

### ISSUE THREAD

**Issue by LazloBodi** [aws/aws-ssm-data-protection-provider-for-aspnet#15]
When my application wanted to fetch data from SSM and the IAM role hasn't got permission to call GetParametersByPath, the issue was logged but my application started anyway.
I would like to make the startup fail when it hasn't got permission. How can achieve this?

**Comment by normj** [comment]
This library is letting the IAM permissions exception bubble up but ASP.NET Core is trapping the exception so I don't think there is much else we can from this library. Agree with you though that it would be better to fail fast in this case.
