### ISSUE TITLE
Bug: Long running services fail to fetch when session token expires

### ISSUE THREAD

**Issue by StummeJ** [aws/aws-ssm-data-protection-provider-for-aspnet#18]
We have a long running service being hosted in ECS.  After the session token expires, data protection fails to fetch the encryption keys.

It looks like things are getting registered as singletons and my hunch is that this will not get the latest environment variables after the token has expired.

**Comment by StummeJ** [comment]
Further digging I've noticed that it *should* be getting the latest credentials... so maybe ECS isn't refreshing the tokens?

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bnetstandard/EnvironmentVariablesAWSCredentials.cs#L66

**Comment by ashishdhingra** [comment]
Hi @StummeJ,

You are correct. Temporary credentials have an expiration interval. When credentials expire, any calls made with those credentials will fail. So, application must then request new set of credentials. Please refer the link [Using temporary credentials with AWS resources](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) for more details.

Please let me know if this answers the question and if this issue could be closed.

Thanks,
Ashish

**Comment by StummeJ** [comment]
Yup, we found a different provider.  I think it would be good to add documentation around running on ecs.

**Comment by ashishdhingra** [comment]
@StummeJ Thanks. I will close this issue. The link [How Amazon Elastic Container Service Works with IAM](https://docs.aws.amazon.com/AmazonECS/latest/userguide/security_iam_service-with-iam.html) specifies ECS support of using  temporary credentials. It's a general guideline to refresh temporary credentials when they expire.
