### ISSUE TITLE
v1.1.0 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but latest is 3.5.1.5

### ISSUE THREAD

**Issue by YuxuanLin** [aws/aws-ssm-data-protection-provider-for-aspnet#20]
## Description

The latest verion v1.1.0 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but latest AWSSDK.Core is 3.5.1.5.

Please update your dependency up to latest too.

### Environment

* Build Version: v1.1.0
* OS Info:  OSX Mojave
* Build Environment:  JetBrain Rider
* Targeted .NET Platform:  .net core 3.1

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

PR: https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/pull/21

---

This is a :bug: bug-report

**Comment by zachsawcs** [comment]
Lol looks like AWS forgot to update their dependent nuget packages when they upgraded AWSSDK.Core to 3.5. A lot of packages are still left with a < 3.4.0 constraint. How can this be "forgotten" when there are tools (i.e. IDE, dotnet build a project etc) that would catch problems like this automatically is... beyond me.

**Comment by ashishdhingra** [comment]
Hi @YuxuanLin, 

Thanks for reporting the issue. I will bring this to developer's attention and discuss about plan to update dependencies.

Regards,
Ashish

**Comment by ashovlin** [comment]
We've just released version 2.0.0 of this library with the 3.5 AWS SDK dependency. Thanks.
