### ISSUE TITLE
Upgrade version of AWSSDK.SimpleSystemsManagement from 3.3.102.2 to 3.5.*.* to have compatibility with other AWS Packages

### ISSUE THREAD

**Issue by maulik-modi** [aws/aws-ssm-data-protection-provider-for-aspnet#22]
**Steps to reproduce:**
1. Try adding AWSSDK.SecurityToken (Latest version) and Amazon.AspNetCore.DataProtection.SSM  in asp.net core 3.1 API project.

**Error message:**
![image](https://user-images.githubusercontent.com/34910430/94535182-e1003280-025e-11eb-9e43-f36da7ceb138.png)

**Scenario**
We need to use ASP.NET Core data protection/persistence and Assume Role in Microservice project for compliance reason.

**Root cause**
Hence, we would like to use AWSSDK.SecurityToken and Amazon.AspNetCore.DataProtection.SSM but looks like both require incompatible version of AWS SDK. 

**Suggested action**
Kindly release a new version of package with upgraded version of AWSSDK.SimpleSystemsManagement.

**Comment by ashovlin** [comment]
We've just released version 2.0.0 of this library with the 3.5 AWS SDK dependency. Thanks.
