### ISSUE TITLE
When will 1.2.0 be released?

### ISSUE THREAD

**Issue by jarz** [aws/aws-ssm-data-protection-provider-for-aspnet#23]
The version was bumped almost a month ago with needed changes to dependencies.

When will v1.2.0 be released/pushed to NuGet?
---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @jarz,

Thanks for posting the question. I will discuss the same with the development team for the updates.

Regards,
Ashish

**Comment by ashovlin** [comment]
We've just released version 2.0.0 of this library with the 3.5 AWS SDK dependency. Thanks.
