### ISSUE TITLE
Is the compatibility line a requirement to use this package?

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-ssm-data-protection-provider-for-aspnet#26]
I'm wondering if the compatibility line is a requirement to use this package?

```
services.AddMvc()
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

Ideally I wouldn't want to set this compatibility.

**Comment by ashishdhingra** [comment]
Hi @raRaRa,

Good morning.

MSDN documentation [Compatibility version for ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-2.1) provides some guidance on the use of `.SetCompatibilityVersion()`. The last commit for this library with code changes was approximately 1.7 years ago. To protect apps from any breaking changes introduced in ASP.NET Core 2.2 version, this call might have been necessary. I would need to check with developer to have a look at it.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @raRaRa,

Based on my discussion with developer, the `.SetCompatibilityVersion()` should not be required. I have created a PR #27 to update the `Readme.md`.

Thanks,
Ashish

**Comment by raRaRa** [comment]
Thank you for the quick response to this matter @ashishdhingra - appreciate it!
