### ISSUE TITLE
Running into an issue when running locally

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-ssm-data-protection-provider-for-aspnet#29]
For some reason the data protection fails when running locally. It will eventually timeout with the error:

`{"An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information."}`

The inner exception has this message: `No such host is known.`

But it seems to work just fine when running on AWS in a Lambda. Is there anything specific I need to do locally? E.g. pass the AWS Credentials somehow to the AmazonSimpleSystemsManagementClient in the extension?

**Comment by ashishdhingra** [comment]
Hi @raRaRa,

Good morning.

Please share the sample code solution in order to troubleshoot the issue. Also, for accessing any service API operation, credentials need to be passed. Kindly check on how credentials are configured (e.g. in shared credentials file, passed directly to service client constructor, etc.).

Thanks,
Ashish

**Comment by shaunbowe** [comment]
I ran into this same issue. In my instance I am running a .net core 3.1 project and I have the AWS CLI installed and configured.

Adding this line right before fixed the issue for me
```
services.AddSingleton<IAmazonSimpleSystemsManagement>(new AmazonSimpleSystemsManagementClient());
services.AddDataProtection().PersistKeysToAWSSystemsManager("keyhere");
```

When I didn't add that line if I called .GetService<IAmazonSimpleSystemsManagement> the client was not setup. It used a region called DefaultRegion which seems invalid.

**Comment by shaunbowe** [comment]
Canceling bot. Still broken..

**Comment by ashishdhingra** [comment]
Hi @raRaRa,

I tested running simple AWS Serverless Lambda application locally on windows and it works perfectly fine. I used `ASP.NET Core Web App` for AWS Serverless template using Visual Studio:
**.csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>

    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.DataProtection.SSM" Version="2.0.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="5.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>
</Project>
```
**Startup.cs**
``` C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace SystemManagerDataProtection_Issue29
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddDataProtection().PersistKeysToAWSSystemsManager("/MyApplication/DataProtection");
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
    }
}
```

After running the application locally, it generated the entry `/MyApplication/DataProtection/key-<guidstring>` in System Manager parameter store:
<img width="1505" alt="Screen Shot 2021-01-08 at 5 04 28 PM" src="https://user-images.githubusercontent.com/67916761/104078549-9c782180-51d3-11eb-9978-47505cde56d9.png">

Kindly note that while generating project from Visual Studio AWS template, it generates `appsettings.Development.json` as follows:
```JSON
{
  "AWS": {
    "Region": "DefaultRegion"
  }
}
```
You would need to change region to an actual region (such as `us-east-2`) for it to work.

Please let me know if this helps and if it resolves your issue.

Thanks,
Ashish
