### ISSUE TITLE
Why is a leading slash being added to SSM parameter name?

### ISSUE THREAD

**Issue by ljvanschie** [aws/aws-ssm-data-protection-provider-for-aspnet#32]
When using `PersistKeysToAWSSystemsManager("my-service")`, a parameter is created like `/my-service-..`, instead of `my-service-..`. What is the reasoning for this behavior?

https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/src/Amazon.AspNetCore.DataProtection.SSM/SSMXmlRepository.cs#L72

In our setup, each microservice gets permission to read/write SSM parameters starting with a certain namespace (in this case, it would be `my-service.*`). This does not work, because of the leading slash. It would be nice if this could be omitted, perhaps by configuration.

**Comment by ashishdhingra** [comment]
Hi @ljvanschie,

Good morning.

Thanks for posting guidance question. Please refer to [Creating Systems Manager parameters](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html) for requirements and constraints for parameter names. The slash character ( / ) is used to delineate hierarchies in parameter names. XML represents hierarchal nature, hence, this could be the reason that parameter names are always prefixed with `/` character. Also refer example on the page https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet.

Hope this helps.

Thanks,
Ashish
