### ISSUE TITLE
Make `parameterNamePrefix` possible to specify in configuration or at least make `SSMXmlRepository` public

### ISSUE THREAD

**Issue by agilenut** [aws/aws-ssm-data-protection-provider-for-aspnet#35]
## Describe the Feature
I need to be able to pull `parameterNamePrefix` from configuration. My need is similar to issue #8. 

### Is your Feature Request related to a problem?
Yes, I need to pull the `parameterNamePrefix` value from configuration. This part of the startup configuration has to be in a shared library where other items are also setup. So, it is not straight-forward for me to have the consumer pull the configuration and pass it in. 

## Proposed Solution
I would have preferred that you had merged PR #9. However, since you didn't, I could work around this issue if you made `SSMXmlRepository` public. If it was public, I could duplicate some of the logic that you have added in `ExtensionMethods` to configure the `KeyManagementOptions` and pull from the known configuration location as a part of that registration. 

### Describe alternatives you've considered
In the shared library, I have to setup multiple service registrations which will come from different areas of config. The configuration structure will be well known. So, my goal is to avoid having the user pass in all of the different configuration sections that are needed (DataProtection, DistributedCache, Authentication, etc). Instead, during registration, I need to look for the config that exists in the known locations and reduce the burden to the caller. Since `parameterNamePrefix` is not currently a part of an options class and `SSMXmlRepository` is internal, the only other option I see for me to accomplish my goal is to use reflection to instantiate the internal repository. I'd rather not do this. 

## Additional Context
See above

### Environment
N/A

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Needs review with the team to make `SSMXmlRepository` public since the 1st ask was no go in https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/pull/9.

**Comment by ashishdhingra** [comment]
Closing due to lack of traction.
