### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by girishnuli** [aws/aws-ssm-data-protection-provider-for-aspnet#4]
I put this provider in a .net core 2.1.5 webapi and deployed it to a lambda function. API endpoint works fine, but cloudwatch logs the below error:

Amazon.AspNetCore.DataProtection.SSM.SSMXmlRepository: Error calling SSM to get parameters starting with /LambdaWebApi.DataProtection/: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/lambdawebapiservice-dev-us-east-1-lambdaRole/lambdawebapiservice-dev-api is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-1:xxxxxxxxxxxx:parameter/LambdaWebApi.DataProtection/

Note:I have replaced the arn number with xxxxxxxxxxxx in the above copy-pasted error message.

Since the data protection system is not set due to above error, the api throws the below error:
[Error] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: An error occurred while reading the key ring. 

Is there some IAM permission that must be setup before using this library? Any help is appreciated. Thanks.

**Comment by girishnuli** [comment]
Adding a policy in IAM for the lambda role to allow it access to SSM resolved the problem. Please close this issue.

**Comment by jmosbech** [comment]
I'm having the same issue.

What is the minimum required set of permissions needed to make the library work?

**Comment by normj** [comment]
I added a permissions section to the README. I would appreciate feedback if that is helpful.

https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/README.md#permissions

**Comment by jmosbech** [comment]
This is perfect. I came up with the same results by inspecting the error messages, but this makes it a lot easier to get started. Thanks!
