### ISSUE TITLE
RELEASE.CHANGELOG.md is missing version 3.0.0

### ISSUE THREAD

**Issue by roemba** [aws/aws-ssm-data-protection-provider-for-aspnet#44]
### Describe the issue

It seems that when version 3.0.0 was released, @normj updated the RELEASE.CHANGELOG.md by copy pasting the header of the previous 2.1.0 release and changing the contents. However, they forgot to change the version number of the release so now there are two 2.1.0 releases in the RELEASE.CHANGELOG.md while the latest should be 3.0.0

Should be a simple fix and helps with confusion for people looking to upgrade to 3.0.0 and wanting to know what has changed. I, for one, had trouble finding the breaking changes :sweat_smile: 

### Links

https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/RELEASE.CHANGELOG.md

**Comment by ashishdhingra** [comment]
Appears to be a simple change after looking at the RELEASE.CHANGELOG.md.

**Comment by ashishdhingra** [comment]
Fixed in latest commit.
