### ISSUE TITLE
Readme is incorrect as latest changes have not been released on NuGet yet

### ISSUE THREAD

**Issue by Bio2hazard** [aws/aws-ssm-data-protection-provider-for-aspnet#5]
The 1.0.0 version released on NuGet does not include `builder.Services.TryAddAWSService<IAmazonSimpleSystemsManagement>();`  but the readme.md was recently modified to remove that line from the usage instructions.

I would suggest either cutting a new NuGet release or re-adding the line to the readme until 1.0.1 is released.

**Comment by normj** [comment]
The `TryAddAWSService` method comes from the [AWSSDK.Extensions.NETCore.Setup](https://www.nuget.org/packages/AWSSDK.Extensions.NETCore.Setup/) NuGet package. You can use that method to make sure an IAmazonSimpleSystemsManagement instance is provided to this NuGet package.

**Comment by Bio2hazard** [comment]
I think you misunderstood. 

What I am trying to say is that the 1.0.0 package released on NuGet does not contain the TryAddAWSService line. That line must have been added after the 1.0 version was released. 

I followed the instructions and got an error that IAmazonSimpleSystemsManagement is not registered in the DI Container.

Here is the decompiled source for the nuget package:
![image](https://user-images.githubusercontent.com/2462038/52232019-3b6da380-2870-11e9-8057-a34b353a30e6.png)

Please note that the TryAddAWSService is not there. 
So I am suggesting either cutting a new 1.0.1 release with the updated source code, or adding the line back to the readme.
