### ISSUE TITLE
Add support of Intelligent-Tiering parameter tier

### ISSUE THREAD

**Issue by DenisDoroshko** [aws/aws-ssm-data-protection-provider-for-aspnet#57]
### Describe the feature

AWSSDK supports `Inteligent-Tiering` for SSM parameters so would be nice to add this option to this package as well

### Use Case

Some of our accounts can use `Standard` parameters and others can use only `Advanced` so we want to apply `Inteligent-Tiering` to create `Standard` parameters where it's possible

### Proposed Solution

Add new enum option https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/src/Amazon.AspNetCore.DataProtection.SSM/TierStorageMode.cs
And update logic in `SSMXmlRepository` if it will be required https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/blob/master/src/Amazon.AspNetCore.DataProtection.SSM/SSMXmlRepository.cs#L192

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.AspNetCore.DataProtection.SSM 3.1.0

### Targeted .NET Platform

.NET7

### Operating System and version

Windows 10, Linux

**Comment by ashishdhingra** [comment]
AWS SDK for .NET has [ParameterTier](https://github.com/aws/aws-sdk-net/blob/bf57bd9bcbc694a2761e7bcc38a7e31106c21bc8/sdk/src/Services/SimpleSystemsManagement/Generated/ServiceEnumerations.cs#L3756C18-L3756C31) constant class generated in Service Enumerations. Perhaps support this the same way instead of standard enumeration.

Needs review with the team.

**Comment by ashishdhingra** [comment]
This has been released in [Amazon.AspNetCore.DataProtection.SSM version 3.2.0](https://www.nuget.org/packages/Amazon.AspNetCore.DataProtection.SSM/3.2.0)
