### ISSUE TITLE
Update csproj file to include extra information and make documentation available

### ISSUE THREAD

**Issue by Bio2hazard** [aws/aws-ssm-data-protection-provider-for-aspnet#6]
The following should be added to the csproj file:

```xml
<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
<AssemblyVersion>1.0.0</AssemblyVersion>
<FileVersion>1.0.0</FileVersion>
<Version>1.0.0</Version>
```

This should embed the xml documentation into the package and allow intellisense to pick it up and display it. 👍

**Comment by normj** [comment]
I have made the doc change in the dev branch to go out with the next release.

**Comment by krdmllr** [comment]
You can simplify the doc property if you want
Instead of this
```<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>```
Use this
```<GenerateDocumentationFile>true</GenerateDocumentationFile>```
