### ISSUE TITLE
`ParameterNamePrefix` Should be Retrievable from Configuration

### ISSUE THREAD

**Issue by chrisoverzero** [aws/aws-ssm-data-protection-provider-for-aspnet#8]
Given that the library already has a `PersistOptions`, it would be more idiomatic to ASP.NET Core to allow that value of `parameterNamePrefix` to be retrieved from configuration, rather than passed into the `PersistKeysToAWSSystemsManager` extension method.

Additionally, this would allow the value to be set from a CloudFormation template by setting an environment variable. Or, really, set by any of the practically infinite ways to set a configuration value, rather than a literal string in executable code.

I have a PR for this ready to go, which I'll link after I create it.

**Comment by normj** [comment]
Closing as we decided not to do this via the PR https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/pull/9
